[book]
authors = ["Jasper"]
language = "de"
multilingual = false
src = "src"
title = "Förderverein Inselmäuse: Satzung und Ordnungen"

[output.html]
no-section-label = true
cname = "satzung.inselmaus.de"
